# Generated by Django 4.0.5 on 2022-06-14 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('img_url', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=256)),
                ('starting_bid', models.FloatField(max_length=64)),
                ('watchlist_items', models.ManyToManyField(null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
