# Generated by Django 4.0.5 on 2022-06-14 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='watchlist_items',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='watchlist_users',
            field=models.ManyToManyField(null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
